version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: gutendex
      POSTGRES_USER: gutendex
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn gutendex.wsgi:application --bind 0.0.0.0:8000
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "true"
      SECRET_KEY: "changeme"
      DATABASE_NAME: gutendex
      DATABASE_USER: gutendex
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      ALLOWED_HOSTS: "*"

volumes:
  postgres_data:
